name: release
on:
  push:
    tags:
      # match semver versions
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-mac:
    runs-on: macOS-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: get node version
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        shell: bash
        id: nvm

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '${{steps.nvm.outputs.NVMRC}}'
          cache: npm

      - name: npm install
        run: npm i --prefer-offline --no-audit

      - name: build
        run: npm run build

      - name: publish
        run: npx --no electron-builder build --mac -c.extraMetadata.main=build/electron/main.js --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_APP_PASSWORD: ${{ secrets.APPLE_ID_APP_PASSWORD }}
